; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L ; Разгон процессора до максимума для стабильного шага

upload_flags =
    --before=default_reset
    --after=hard_reset
    --connect-attempts=15

;Включаем режим отправки строк по нажатию Enter
monitor_filters = send_on_enter